---
title: "Batteries"
subtitle: "Data"
output: html_document
date: "2024-12-13"
---

# Data

```{r setup-01, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)

keep <- ls()

do.sql <- FALSE
if(exists("ipsdi.nfirs") & ("RPostgreSQL" %in% row.names(installed.packages()))){ 
  if(! is.null(ipsdi.nfirs)){
#    library(RPostgreSQL)
#    do.sql <- TRUE
  }
} else {
  ipsdi.nfirs <- NULL
}
library(magrittr)
library(tidyr)
library(dplyr)
#library(sf)

if(! exists("csv_dir")){
  csv_dir <- "csv/"
}
if(! exists("intmdt_dir")){
  intmdt_dir <- "rdata/"
}

# SQL Queries into NFIRS are from IPSDI
cpsc_url <- "https://www.saferproducts.gov/"
tesla_fires <- "https://www.tesla-fire.com/"
```

```{sql b, connection=ipsdi.nfirs, output.var="data.summ.b", eval=do.sql}
WITH t AS (
  SELECT DISTINCT
    code_value,
	code_descr
  FROM codelookup
  WHERE fieldid ~* 'inc_type'
), p AS (
  SELECT DISTINCT
    code_value,
	code_descr
  FROM codelookup
  WHERE fieldid ~* 'prop_use'
)
SELECT 
  extract(year from inc_date) as year,
  t.code_descr AS inc_type, 
  CASE 
    WHEN prop_use in ('965', '880', '881', '882') THEN 'Parking'
    WHEN substring(prop_use from 1 for 2) in ('92', '96') THEN 'Roadway'
	ELSE p.code_descr
  END as prop_use,
  count(*) as fires,
  sum(
    CASE
	  WHEN equip_inv = '229' THEN 1
	  ELSE 0
	END) AS battery

FROM fireincident f JOIN basicincident b USING (state, fdid, inc_date, inc_no, exp_no)
     LEFT JOIN t ON substring(b.inc_type from 1 for 2) = t.code_value
     LEFT JOIN p ON substring(b.prop_use from 1 for 1) = p.code_value
GROUP BY
  extract(year from inc_date),
  t.code_descr, 
  CASE 
    WHEN prop_use in ('965', '880', '881', '882') THEN 'Parking'
    WHEN substring(prop_use from 1 for 2) in ('92', '96') THEN 'Roadway'
	ELSE p.code_descr
  END
```

```{sql a, connection=ipsdi.nfirs, output.var="data.summ", eval=do.sql}
/*
  This provides summary information about the number of battery fires in NFIRS,
  relative to the total number of fires, and some idea of the casualty rate, 
  again in comparison to that of non-battery fires.

   This data, as will all SQL queries in this document, comes from the 
   International Public Safety Data Institute.                        */
with it as (
  SELECT DISTINCT 
    code_value as v,
	code_descr as d
  FROM codelookup
  WHERE fieldid ~* 'inc_type'
)

SELECT
  extract(year from inc_date) as year,
  substring(inc_type from 1 for 2) as inc_type,
  it.d as type_descr,
  count(*) as fires,
  sum(
	  CASE 
	    WHEN coalesce(ff_death, 0) + coalesce(ff_inj, 0) + coalesce(oth_death, 0) + coalesce(oth_inj, 0) > 0 THEN 1
		ELSE 0
	  END
  ) as casualties,
  sum(
	  CASE 
	    WHEN coalesce(ff_death, 0) + coalesce(oth_death, 0) > 0 THEN 1
		ELSE 0
	  END
  ) as deaths,
  sum(
  	CASE 
	  WHEN equip_inv = '229' THEN 1
	  ELSE 0
  	END
  ) as battery_fires,
  sum(
	  CASE 
	    WHEN
		  equip_inv = '229' AND
		  coalesce(ff_death, 0) + coalesce(ff_inj, 0) + coalesce(oth_death, 0) + coalesce(oth_inj, 0) > 0 THEN 1
		ELSE 0
	  END
  ) as battery_casualties,
  sum(
	  CASE 
	    WHEN
		  equip_inv = '229' AND
		  coalesce(ff_death, 0) + coalesce(oth_death, 0) > 0 THEN 1
		ELSE 0
	  END
  ) as battery_deaths,

	sum(
		CASE
			WHEN fire_sprd in ('1', '2', '3', '4', '5') THEN 1
			ELSE 0
		END
	) as sev,
	sum(
		CASE
			WHEN fire_sprd in ('2', '3', '4', '5') THEN 1
			ELSE 0
		END
	) as room,
	sum(
		CASE
			WHEN fire_sprd in ('3', '4', '5') THEN 1
			ELSE 0
		END
	) as struc,
	sum(
		CASE
			WHEN fire_sprd in ('5') THEN 1
			ELSE 0
		END
	) as beyond	

FROM fireincident LEFT JOIN basicincident USING (state, fdid, inc_date, inc_no, exp_no)
                  LEFT JOIN it ON (substring(inc_type from 1 for 2) = it.v)
WHERE inc_type ~* '^1'
GROUP BY
  extract(year from inc_date),
  substring(inc_type from 1 for 2),
  it.d
ORDER BY
  extract(year from inc_date),
  substring(inc_type from 1 for 2),
  it.d
```

```{sql selected, connection=ipsdi.nfirs, output.var="selected", eval=do.sql}
SELECT 
  state,
  fdid,
  fd_name,
  extract(year from inc_date) as year,
  CASE
    WHEN equip_inv = '229' THEN 'Battery' 
    ELSE 'Other' 
  END as type,
  count(*) as total,
  sum(
    CASE 
      WHEN inc_type ~* '^11' THEN 1
      ELSE 0
    END
  ) AS structure,
  sum(
    CASE 
      WHEN inc_type ~* '^13' THEN 1
      ELSE 0
    END
  ) AS mobile,
  sum(
    CASE 
      WHEN inc_type ~* '^12' THEN 1
      ELSE 0
    END
  ) AS mh, 
  sum(
    CASE 
      WHEN inc_type ~* '^14' THEN 1
      ELSE 0
    END
  ) AS veg,
  sum(
    CASE 
      WHEN inc_type ~* '^15' THEN 1
      ELSE 0
    END
  ) AS rubbish,
  sum(
    CASE 
      WHEN inc_type ~* '^16' THEN 1
      ELSE 0
    END
  ) AS special,
  sum(
    CASE 
      WHEN inc_type ~* '^17' THEN 1
      ELSE 0
    END
  ) AS crop,
  sum(
    CASE 
      WHEN inc_type ~* '^10' THEN 1
      ELSE 0
    END
  ) AS other,
  sum(
    CASE 
      WHEN inc_type ~* '^[^1]' or inc_type = '' or inc_type is null THEN 1
      ELSE 0
    END
  ) AS not_fire  
--  inc_type,
--  fire_sprd,
--  eq_power,
--  eq_brand,
--  eq_model
FROM basicincident LEFT JOIN fireincident USING (state, fdid, inc_date, inc_no, exp_no)
                   LEFT JOIN fdheader USING (state, fdid)
WHERE
--equip_inv = '229' and
  ((state = 'CA' AND fdid in ('01065', '19105', '30020', '30065', '33090', '38005')) OR
  (state = 'CO' AND fdid in ('00180', '00520', '05909')) OR
  (state = 'FL' AND fdid in ('01023', '04112', '06301')) OR
  (state = 'GA' AND fdid in ('03301')) OR
  (state = 'HI' AND fdid in ('52000')) OR
  (state = 'IL' AND fdid in ('CS931')) OR
  (state = 'KY' AND fdid in ('34155')) OR
  (state = 'NJ' AND fdid in ('09013')) OR
  (state = 'NV' AND fdid in ('03050')) OR
  (state = 'NY' AND fdid in ('24001')) OR
  (state = 'VA' AND fdid in ('04100')) OR
  (state = 'WA' AND fdid in ('17M15', '27D06')) OR
  (state = 'WI' AND fdid in ('05040')))

group by 
  state,
  fdid,
  fd_name,
  extract(year from inc_date),
  CASE
    WHEN equip_inv = '229' THEN 'Battery' 
    ELSE 'Other' 
  END

order by 
  state,
  fdid,
  extract(year from inc_date)

```

```{sql tesla-vin, connection=ipsdi.nfirs, output.var="tesla", eval=FALSE}
-- This is an older version of an analysis that is now performed much better.
-- It is now obsolete and therefore not run.
SELECT 
  extract(year from inc_date) as year,
  sum(
    CASE 
      WHEN mob_vin_no ~* '^(5YJ|7SA|LRW|XP7|SFZ)' THEN 1
      WHEN equip_inv = '229' THEN 1
      ELSE 0
    END
  ) AS total, 
  sum(
    CASE 
      WHEN mob_vin_no ~* '^(5YJ|7SA|LRW|XP7|SFZ)' THEN 1
      ELSE 0
    END
  ) AS tesla 
FROM basicincident LEFT JOIN fireincident USING (state, fdid, inc_date, inc_no, exp_no)
                   LEFT JOIN fdheader USING (state, fdid)
WHERE
--  equip_inv = '229' and
  inc_type ~* '^13'

group by 
  extract(year from inc_date)

order by 
  extract(year from inc_date)
```

```{sql tesla-vin1, connection=ipsdi.nfirs, output.var="tesla_detail", eval=FALSE}
-- Just like the table above, this is now obsolete.
SELECT 
  state,
  inc_date,
  extract(year from inc_date) as year,
  mob_year,
  CASE
    WHEN equip_inv ~* '22[89]' THEN 'Yes'
	ELSE 'No'
  END as battery,
  mob_invol,
  CASE
    WHEN mob_invol in ('2', '3') THEN 'Yes'
	ELSE 'No'
  END AS ignited,
  CASE
    WHEN mob_invol in ('1', '3') THEN 'Yes'
	ELSE 'No'
  END AS burned,
  mob_type
FROM basicincident LEFT JOIN fireincident USING (state, fdid, inc_date, inc_no, exp_no)
                   LEFT JOIN fdheader USING (state, fdid)
WHERE
  mob_vin_no ~* '^(5YJ|7SA|LRW|XP7|SFZ)' and
  inc_type ~* '^13'

order by 
  extract(year from inc_date)
```

```{sql tesla-vin-inc, connection=ipsdi.nfirs, output.var="car.actions", eval=do.sql}
with mk as (
	SELECT DISTINCT code_value, code_descr from codelookup where fieldid ~* 'mob_make'
), b1 as (
SELECT 
  state,
  fdid,
  fd_name,
  extract(year from inc_date) as year,
  'Tesla' AS tesla,
  mk.code_descr as make,
  mob_model,
  mob_year,
  mob_vin_no,
  equip_inv,
  act_tak1,
  act_tak2,
  act_tak3
FROM basicincident b LEFT JOIN fireincident f USING (state, fdid, inc_date, inc_no, exp_no)
                     LEFT JOIN fdheader h USING (state, fdid)
					 LEFT JOIN mk ON (f.mob_make = mk.code_value)
WHERE
  inc_type ~* '^13' and 
  --  equip_inv = '229' and
  mob_vin_no ~* '^(5YJ|7SA|LRW|XP7|SFZ)' and 
  mob_type ~* '^1|NN'
), b2 AS (
SELECT 
  state,
  fdid,
  fd_name,
  extract(year from inc_date) as year,
  'Other' AS tesla,
  mk.code_descr as make,
  mob_model,
  mob_year,
  mob_vin_no,
  equip_inv,
  act_tak1,
  act_tak2,
  act_tak3
FROM basicincident b LEFT JOIN fireincident f USING (state, fdid, inc_date, inc_no, exp_no)
                     LEFT JOIN fdheader h USING (state, fdid)
					 LEFT JOIN mk ON (f.mob_make = mk.code_value)
WHERE
  inc_type ~* '^13' and 
  equip_inv = '229' and
--mob_vin_no ~* '^(5YJ|7SA|LRW|XP7|SFZ)' and 
  mob_type ~* '^1|NN'
limit 100
)
select * from b1
UNION
select * from b2
order by 
  tesla,
  mob_vin_no
```

```{sql vin-vehicles, connection=ipsdi.nfirs, output.var="car.fires", eval=FALSE}
with typ as (
Select DISTINCT * From codelookup Where fieldid ~* 'mob_type'
), mk as (
Select DISTINCT * From codelookup Where fieldid ~* 'mob_make'
)

Select 
  f.state,
  fd_name,
  f.inc_date,
  city,
  CASE 
    WHEN mob_invol in ('2', '3') THEN True
    ELSE False
  END AS ignited,
  CASE 
    WHEN mob_invol in ('1', '3') THEN True
    ELSE False
  END AS burned,
  coalesce(typ.code_descr, mob_type) AS mob_type,
  coalesce(mk.code_descr, mob_make) AS mob_make,
  mob_model,
  mob_year,
  mob_vin_no,
  inc_type,
  prop_use,
  coalesce(ff_death, 0) + coalesce(oth_death, 0) AS deaths
From fireincident f LEFT JOIN basicincident b USING (state, fdid, inc_date, inc_no, exp_no)
                    LEFT JOIN incidentaddress USING (state, fdid, inc_date, inc_no, exp_no)
                    LEFT JOIN fdheader USING (state, fdid) 
                    LEFT JOIN typ ON mob_type  = typ.code_value 
                    LEFT JOIN mk  ON mob_make  = mk.code_value
Where coalesce(mob_vin_no, '') != ''
```

```{sql car-summ, connection=ipsdi.nfirs, output.var="car.summ", eval=do.sql}
Select 
  extract(year from inc_date) AS year,
  count(*) as cars,
  sum(
    CASE
	  WHEN coalesce(mob_vin_no, '') != '' THEN 1
	  ELSE 0
	END
  ) as vins
From fireincident 
WHERE mob_invol in ('1', '2', '3')
GROUP BY
  extract(year from inc_date)
ORDER BY
  extract(year from inc_date)
```

```{sql firelist, connection=ipsdi.nfirs, output.var="structures", eval=do.sql}
WITH d AS (
/*  Select the departments I am interested in.
      Departments with at least 600 structure fires since 2010 and at least 
      one battery fire in that time.
*/
SELECT
  state,
  fdid,
  count(*) as n,
  sum(
    CASE
      WHEN equip_inv = '229' THEN 1
      ELSE 0
    END
) AS batteries
FROM fireincident JOIN basicincident USING (state, fdid, inc_date, inc_no, exp_no)
WHERE 
  inc_type ~* '^11' AND
  extract(year from inc_date) > 2010
GROUP BY
  state,
  fdid
HAVING 
  count(*) > 600 AND
  sum(
    CASE
      WHEN equip_inv = '229' THEN 1
      ELSE 0
    END
  ) > 0
)
SELECT
  state,
  fdid,
  fd_name,
  extract(year from inc_date) as year,
  count(*) as fires,
  sum(
    CASE
      WHEN equip_inv = '229' THEN 1
      ELSE 0
    END
  ) AS batteries
FROM 
  fireincident JOIN basicincident USING (state, fdid, inc_date, inc_no, exp_no)
               JOIN d USING (state, fdid) 
               LEFT JOIN fdheader USING (state, fdid)
WHERE
  inc_type ~* '^11'
GROUP BY 
  state,
  fdid,
  fd_name,
  extract(year from inc_date)
```

```{sql firedetails, connection=ipsdi.nfirs, output.var="details", eval=do.sql}
WITH a AS (
  SELECT DISTINCT *
  FROM codelookup
  WHERE fieldid ~* 'area_orig'
), p AS (
  SELECT DISTINCT *
  FROM codelookup
  WHERE fieldid ~* 'prop_use'
), h AS (
  SELECT DISTINCT *
  FROM codelookup
  WHERE fieldid ~* 'heat_sourc'
), f AS (
  SELECT DISTINCT *
  FROM codelookup
  WHERE fieldid ~* 'first_ign'
)
SELECT
  state,
  fdid,
  fd_name,
  inc_date,
  extract(year from inc_date) as year,
  extract(month from inc_date) as month,
  prop_use,
  p.code_descr as property,
  CASE
    WHEN coalesce(ff_death,  0) > 0 THEN 'Yes'
    WHEN coalesce(ff_inj,    0) > 0 THEN 'Yes'
    WHEN coalesce(oth_death, 0) > 0 THEN 'Yes'
    WHEN coalesce(oth_inj,   0) > 0 THEN 'Yes'
	ELSE 'No'
  END as casualties,
  extract(hour from alarm) as tod,
  area_orig,
  a.code_descr as room,
  heat_sourc,
  h.code_descr as heat,
  first_ign,
  f.code_descr as ifi,
  CASE
    WHEN mob_invol in ('1', '2', '3') THEN 'Yes'
	ELSE 'No'
  END as mob_invol,
  fire_sprd,
  city,
  state_id,
  zip5,
  concat_ws(', ', sup_fac_1, sup_fac_2, sup_fac_3) as sup_fac--,
--st_AsEWKT(geom) as wkt
FROM 
  fireincident JOIN basicincident USING (state, fdid, inc_date, inc_no, exp_no)
               LEFT JOIN incidentaddress USING (state, fdid, inc_date, inc_no, exp_no)
               LEFT JOIN fdheader USING (state, fdid) 
               LEFT JOIN a ON (area_orig  = a.code_value)
               LEFT JOIN p ON (prop_use   = p.code_value)
               LEFT JOIN h ON (heat_sourc = h.code_value)
               LEFT JOIN f ON (first_ign  = f.code_value)
WHERE
  inc_type ~* '^11' AND
  equip_inv = '229' AND
  extract(year from inc_date) > 2010
```

```{r not_sql, eval=! do.sql}
# Since all the sql queries were actually conducted off-line (and are disabled above)
# this loads the downloaded csv files and is what actually loads the data
data.summ <- paste0(csv_dir, "summary.csv") %>% read.csv()
data.summ.b <- paste0(csv_dir, "summary.b.csv") %>% read.csv()
selected <- paste0(csv_dir, "selected.csv") %>% read.csv()
tesla <- paste0(csv_dir, "tesla.summ.csv") %>% read.csv()
tesla_detail <- paste0(csv_dir, "Tesla.csv") %>% read.csv()
car.actions <- paste0(csv_dir, "action.taken.csv") %>% read.csv()
# car.fires <- paste0(csv_dir, "car.fires.zip") %>% unz("car.fires.csv", "r") %>% read.csv()
car.fires.a <- paste0(csv_dir, "car.fires.a.zip") %>% unz("car.fires.a.csv", "r") %>% read.csv()
car.fires.b <- paste0(csv_dir, "car.fires.b.zip") %>% unz("car.fires.b.csv", "r") %>% read.csv()
car.fires <- rbind(car.fires.a, car.fires.b)
structures <- paste0(csv_dir, "structures.csv") %>% read.csv()
details <- paste0(csv_dir, "details.new.csv") %>% read.csv()
```

```{r more-details, eval=FALSE}
# There is a little bit of massaging to do with `details`
# Most of this is getting the geocoding right. 
# But the geocoding isn't right: try the following code:
# details %>% st_coordinates() %>% as.data.frame() %>% mutate(choose=Y < 0) %>% with(table(choose))
# The fact that there are latitudes less than zero means that some 91 records got latitude and 
# longitude mixed up. So, this deletes the geocoding information. 
# To get it back, uncomment the following lines.

#details <- details$wkt %>% strsplit(";") %>% do.call("rbind", .) %>% as.data.frame() %>% 
#           setNames(c("srid", "geom")) %>% cbind(details, .)
#details$geom[details$geom == "NULL"] <- "POINT EMPTY"
#details <- st_as_sf(details, wkt="geom")
#srid <- details$srid %>% stringr::str_extract("[0-9]+") %>% as.integer() %>% magrittr::extract(1)
#st_crs(details) <- srid
#rm(srid)
#details$srid <- NULL
details$wkt <- NULL
# 
details$sup_fac <- trimws(details$sup_fac, which="both", whitespace="[ ,]") %>%
  sub("^$", NA, .)
details$inc_date <- lubridate::ymd(details$inc_date)
```

```{r cpsc-data, eval=! exists("incidents")}
ff <- c("SearchResults_IncidentReport_02102025_0816.csv",
        "SearchResults_IncidentReport_02142025_1346.csv") %>% paste0(csv_dir, .)
incidents <- rbind(read.csv(ff[1], skip=1),
                   read.csv(ff[2], skip=1))

reports <- grep("^[0-9]",  incidents$Report.No.)
reportz <- grep("^[^0-9]", incidents$Report.No.)

pr <- incidents[reportz, 1:5] %>% 
      setNames(c("Title", "Date", "Text", "Number", "URL")) %>% unique()
incidents <- incidents[reports,] %>% unique()

rm(ff, reports, reportz)

incident.txt <- with(incidents, 
                     paste0(Incident.Description,
                       ifelse(is.na(Company.Comments), "", 
                              paste0("\nCompany Comments: ", Company.Comments))))
```

```{stan base-1, output.var="stan.model"}
data {
  int<lower=0>          S1;         // Number of cars in sample 1
  int<lower=0>          S2;         // Number of cars in sample 2
  int<lower=0>          S12;        // Number of cars in both samples
  int<lower=0, upper=1> zeros;      // = 0: Zeros excluded; =1: zeros allowed
  real                  alpha;      // Parameters used when S12 = 0 and zeros = 1
  real                  scale_p;    // Parameters used when S12 = 0 and zeros = 1
}

transformed data {
  int      which;
  real     theta;
  real     min_N;
  real     scale_N;

  if(S1 <= S2){
    which = 1;
    theta = alpha ^ (1. / S2);
  } else {
    which = 2;
    theta = alpha ^ (1. / S1);
  }
  if(S12 == 0){
    scale_N = sqrt(S1 * S2 / ((1 - alpha ^ (1. / S1)) * (1 - alpha ^ (1. / S2))));
  } else {
    scale_N = S1 * S2 / S12;
  }
  min_N = max(S1, S2) / scale_N;
}

parameters {
  vector<lower=0, upper=1>[2]   p;
  real<lower=min_N>             N_hat;
}

transformed parameters {
  real    N = N_hat * scale_N;
}

model {

  target += lgamma(N + 1) - lgamma(S1 + 1) - lgamma(N - S1 + 1)
            + S1 * log(p[1]) + (N - S1) * log(1 - p[1]);
  target += lgamma(N + 1) - lgamma(S2 + 1) - lgamma(N - S2 + 1)
            + S2 * log(p[2]) + (N - S2) * log(1 - p[2]);
  if(S12 == 0){
    theta ~ beta((1 - p[which]) * scale_p, p[which] * scale_p);
  } else {
    target += lgamma(S1 + 1) - lgamma(S12 + 1) - lgamma(S1 - S12 + 1)
              + S12 * log(p[2]) + (S1 - S12) * log(1 - p[2]);
    if(! zeros){
      target += - log(1 - (1 - p[1] * p[2]) ^ N);
    }
  }
}

generated quantities {
}
```

```{stan slope-1, output.var="stan.mode1"}
// This differs from the version above in that it computes a slope over time
// instead of computing estimated values for each year separately.
data {
  int<lower=1>          T;       // Number of time periods
  vector[T]             S1;      // Sample 1 Counts
  vector[T]             S2;      // Sample 2 Counts
  vector[T]             So;      // Sample Overlap Counts
  int<lower=0, upper=1> slope1;  // 0: No; 1: Yes
  int<lower=0, upper=1> slope2;  // 0: No; 1: Yes
}

transformed data {

  matrix[T,3]    dats = append_col(append_col(S1, S2), So);
  
  real     min_N;
  real     scale_N = 0;
  int      k=0;
  for(i in 1:T){
    if(So[i] > 0){
      scale_N += S1[i] * S2[i] / So[i];
      k = k + 1;
    }
  }
  scale_N = scale_N / k;
  
  min_N = max(append_row(S1, S2)) / scale_N;
}

parameters {
// The affine transformations make sure that Stan's initial sampling occurs
// near the actual expected values. Otherwise bad initial values become too
// common to reliably come up with results.
  vector<offset=-2>[1 + slope1]  p1_lgt;
  vector<offset=-2>[1 + slope2]  p2_lgt;
  real<multiplier=0.25>          r;
  real<lower=min_N>              N_hat;
}

transformed parameters {
  vector[T]    N;
  vector[T]    p1;
  vector[T]    p2;
  for(i in 1:T){
    N[i] = N_hat * scale_N * exp((i - 1) * r);
    if(slope1 == 1){
      p1[i] = inv_logit(p1_lgt[1] + (i - 1) * p1_lgt[2]);
    } else {
      p1[i] = inv_logit(p1_lgt[1]);
    }
    if(slope2 == 1){
      p2[i] = inv_logit(p2_lgt[1] + (i - 1) * p2_lgt[2]);
    } else {
      p2[i] = inv_logit(p2_lgt[1]);
    }
  }
}

model {
  matrix[T, 3]   p_hat = append_col(append_col(p1, p2), p1 .* p2);
  for(i in 1:T){
    for(j in 1:3){
      target += lgamma(N[i] + 1) - lgamma(dats[i,j] + 1) - lgamma(N[i] - dats[i,j] + 1)
              + dats[i,j] * log(p_hat[i,j]) + (N[i] - dats[i,j]) * log(1 - p_hat[i,j]);
  }}
}

generated quantities {
}
```

```{r cleanup-01}
save(data.summ, data.summ.b, selected, structures, details, file=paste0(intmdt_dir, "nfirs.data.RData"))
save(car.fires, car.summ, car.actions, file=paste0(intmdt_dir, "CarFires.data.RData"))
save(incidents, incident.txt, file=paste0(intmdt_dir, "cpsc.data.RData"))
save(incidents, details, file=paste0(intmdt_dir, "recapture.data.RData"))
save(stan.model, stan.mode1, file=paste0(intmdt_dir, "stan.models.RData"))
rm(list=setdiff(ls(), keep))
```